nohup taskset -c 0 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 & 
nohup taskset -c 1 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 2 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 3 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 4 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 5 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 6 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 7 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 8 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 9 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 10 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 11 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 12 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 13 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 14 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 15 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
