nohup taskset -c 0 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 & 
nohup taskset -c 1 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 2 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 3 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 4 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 5 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 6 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 7 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 8 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 9 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 10 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 11 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 12 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 13 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 14 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 15 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 16 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 & 
nohup taskset -c 17 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 18 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 19 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 20 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 21 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 22 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 23 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 24 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 25 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 26 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 27 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 28 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 29 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 30 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
nohup taskset -c 31 python inference/worker.py --queue_name deepalign0 --lease_seconds 200 &
